apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv2
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /opt/nfs  #export dir
    server: 192.168.122.73
  persistentVolumeReclaimPolicy: Retain
